import { BADGE_COLORS, BANNER_COLORS, HIGHLIGHT_COLORS, TEXT_COLORS } from './colors.js'

export interface DoctorDocumentOptions {
  userId?: number
  username?: string
  taskId?: string
}

export function generateDoctorDocument(opts: DoctorDocumentOptions = {}): string {
  const user = opts.username ?? 'me'
  const userId = opts.userId !== undefined ? String(opts.userId) : '0'
  const mention = `:user[${user}]{id="${userId}"}`
  const taskMention = opts.taskId ? `:task[${opts.taskId}]` : ':task[TASK_ID]'

  const textRow = TEXT_COLORS.map(c => `[${c}]{color="${c}"}`).join(' · ')
  const highlightRow = HIGHLIGHT_COLORS.map(c => `[${c}]{highlight="${c}"}`).join(' · ')
  const badgeRow = BADGE_COLORS.map(c => `:badge[${c}]{color="${c}"}`).join(' ')
  const blockRows = TEXT_COLORS.map(c => `${c} block {background="${c}"}`).join('\n\n')
  const banners = BANNER_COLORS.map(c => `::banner{color="${c}"}\nBanner ${c}\n::`).join('\n\n')

  return `# Tight H1
This paragraph must sit directly under the H1 with no extra blank block.

::toc
::

## Why this task exists
Generated by \`cup task-sync doctor\`. Open it in the ClickUp UI and compare against the checks printed to the terminal. Color chips that render as default/unstyled are catalog gaps — add the missing token and re-run doctor.

## Inline marks
**bold**, *italic*, ~~strikethrough~~, \`inline code\`, [link](https://example.com), [underline]{underline}, ${mention}, ${taskMention}

## Text colors
${textRow}

## Highlights
${highlightRow}

## Badges
${badgeRow}

## Block backgrounds
${blockRows}

## Alignment
This is right aligned {align="right"}

## Centered heading {align="center"}
Following paragraph (centered heading is H2).

## Banners
${banners}

::banner{color="blue" icon="🧪"}
Banner with an icon
::

> [!NOTE]
> GitHub NOTE alert → blue banner

> [!WARNING]
> GitHub WARNING alert → yellow banner

> [!CAUTION]
> GitHub CAUTION alert → pink-strong banner

## Quotes
::quote{size="large"}
This is a pull quote (large)
::

> This is a normal block quote

## Headings (tight)
# Heading 1
Para after H1
## Heading 2
Para after H2
### Heading 3
Para after H3
#### Heading 4
Para after H4

## Lists
- Bullet 1
  - Bullet 1.1
    - Bullet 1.1.1
      - Bullet 1.1.1.1
- Bullet 2

1. Ordered 1
   1. Ordered 1.a
2. Ordered 2

- [ ] Unchecked
- [x] Checked
  - [ ] Nested unchecked

## Toggles
::toggle{title="Simple toggle"}
Toggle body paragraph.
::

::toggle{title="Nested parent"}
  :::toggle{title="Nested child"}
  Inner toggle body
  :::
::

::toggle{title="Toggle with code"}
\`\`\`json
{"inside": "toggle"}
\`\`\`
::

## Code
\`\`\`json {lineNumbers}
{"lineNumbers": true, "ok": true}
\`\`\`

\`\`\`javascript
console.log('no line numbers')
\`\`\`

## Divider
---

## Columns
::columns
  :::column{width="0.33"}
  Column A
  :::
  :::column{width="0.33"}
  Column B
  :::
  :::column{width="0.34"}
  Column C
  :::
::

## Tables
::table{widths="120,240,360"}
| Narrow | Medium | Wide explicit |
| --- | --- | --- |
| a | **bold** | [pink]{color="pink"} |
::

::table{widths="75,75,75"}
| A | B | C |
| --- | --- | --- |
| 1 | 2 | 3 |
::

::table{widths="708,75,75"}
| 90 | 10 | 10 |
| --- | --- | --- |
| long | x | y |
::

| Auto A | Auto somewhat longer header |
| --- | --- |
| 1 | 22 |

## Mermaid
\`\`\`mermaid
flowchart LR
  Local[CUFM] --> Compile[compileCufm]
  Compile --> Delta[Quill ops]
  Delta --> ClickUp
\`\`\`

## Button and frame
::button{url="https://example.com" color="#7B68EE"}
Doctor button
::

::frame{src="https://example.com" height="240"}
::

## End
If this paragraph is visible, the document compiled to the end.
`
}
