import { BADGE_COLORS, BANNER_COLORS, HIGHLIGHT_COLORS, TEXT_COLORS } from './colors.js'

export interface DoctorDocumentOptions {
  userId?: number
  username?: string
  taskId?: string
  syncedContent?: { id: string; body: string }
}

const TLDRAW_DOCTOR_SOURCE = JSON.stringify(
  {
    tldrawFileFormatVersion: 1,
    schema: {
      schemaVersion: 1,
      storeVersion: 4,
      recordVersions: {
        asset: {
          version: 1,
          subTypeKey: 'type',
          subTypeVersions: { image: 2, video: 2, bookmark: 0 },
        },
        camera: { version: 1 },
        document: { version: 2 },
        instance: { version: 17 },
        instance_page_state: { version: 3 },
        page: { version: 1 },
        shape: {
          version: 3,
          subTypeKey: 'type',
          subTypeVersions: {
            group: 0,
            embed: 4,
            bookmark: 1,
            image: 2,
            text: 1,
            draw: 1,
            geo: 7,
            line: 0,
            note: 4,
            frame: 0,
            arrow: 1,
            highlight: 0,
            video: 1,
          },
        },
        instance_presence: { version: 4 },
        pointer: { version: 1 },
      },
    },
    records: [
      {
        id: 'document:document',
        typeName: 'document',
        gridSize: 10,
        name: '',
        meta: {},
      },
      {
        id: 'page:page1',
        typeName: 'page',
        name: 'Page 1',
        index: 'a1',
        meta: {},
      },
      doctorGeoShape('shape:source', 'a1', 100, 'CUFM', 'blue'),
      doctorGeoShape('shape:renderer', 'a2', 500, 'tldraw CLI', 'orange'),
      doctorGeoShape('shape:clickup', 'a3', 900, 'ClickUp PNG', 'green'),
      doctorArrowShape('shape:arrow1', 'a4', 'shape:source', 'shape:renderer'),
      doctorArrowShape('shape:arrow2', 'a5', 'shape:renderer', 'shape:clickup'),
    ],
  },
  null,
  2,
)

function doctorGeoShape(id: string, index: string, x: number, text: string, color: string) {
  return {
    id,
    typeName: 'shape',
    type: 'geo',
    parentId: 'page:page1',
    index,
    x,
    y: 100,
    rotation: 0,
    isLocked: false,
    opacity: 1,
    meta: {},
    props: {
      w: 200,
      h: 60,
      geo: 'rectangle',
      color,
      labelColor: 'black',
      fill: 'semi',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text,
      align: 'middle',
      verticalAlign: 'middle',
      growY: 0,
      url: '',
    },
  }
}

function doctorArrowShape(id: string, index: string, from: string, to: string) {
  return {
    id,
    typeName: 'shape',
    type: 'arrow',
    parentId: 'page:page1',
    index,
    x: 0,
    y: 0,
    rotation: 0,
    isLocked: false,
    opacity: 1,
    meta: {},
    props: {
      dash: 'draw',
      size: 'm',
      fill: 'none',
      color: 'black',
      labelColor: 'black',
      bend: 0,
      start: {
        type: 'binding',
        boundShapeId: from,
        normalizedAnchor: { x: 1, y: 0.5 },
        isExact: false,
      },
      end: {
        type: 'binding',
        boundShapeId: to,
        normalizedAnchor: { x: 0, y: 0.5 },
        isExact: false,
      },
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      text: '',
      font: 'draw',
    },
  }
}

export function generateDoctorDocument(opts: DoctorDocumentOptions = {}): string {
  const user = opts.username ?? 'me'
  const userId = opts.userId !== undefined ? String(opts.userId) : '0'
  const mention = `:user[${user}]{id="${userId}"}`
  const taskMention = opts.taskId ? `:task[${opts.taskId}]` : ':task[TASK_ID]'

  const textRow = TEXT_COLORS.map(c => `[${c}]{color="${c}"}`).join(' · ')
  const highlightRow = HIGHLIGHT_COLORS.map(c => `[${c}]{highlight="${c}"}`).join(' · ')
  const badgeRow = BADGE_COLORS.map(c => `:badge[${c}]{color="${c}"}`).join(' ')
  const blockRows = TEXT_COLORS.map(c => `${c} block {background="${c}"}`).join('\n\n')
  const banners = BANNER_COLORS.map(c => `::banner{color="${c}"}\nBanner ${c}\n::`).join('\n\n')
  const syncedContent = opts.syncedContent
    ? `
## Synced Content
::sync-block{id="${opts.syncedContent.id}"}
${opts.syncedContent.body}
::

Below is a clone of the above block:

::sync-block{id="${opts.syncedContent.id}"}
::
`
    : ''

  return `# Tight H1
This paragraph must sit directly under the H1 with no extra blank block.

::toc
::

## Why this task exists
Generated by \`cup task-sync doctor\`. Open it in the ClickUp UI and compare against the checks printed to the terminal. Color chips that render as default/unstyled are catalog gaps — add the missing token and re-run doctor.
${syncedContent}

## Inline marks
**bold**, *italic*, ~~strikethrough~~, \`inline code\`, [link](https://example.com), [underline]{underline}, ${mention}, ${taskMention}

Adjacent spans sharing an emphasis must emit one delimiter pair: **\`SDR\` is the consumed value**: not four asterisks.

*(A fully italic line quoting \`D_max\` inline, so the italic run survives the code span.)*

Mentions stay inline: ${mention} filed ${taskMention} — this trailing text must stay on the same line as the mentions.

## Text colors
${textRow}

## Highlights
${highlightRow}

## Badges
${badgeRow}

## Block backgrounds
${blockRows}

## Alignment
This is right aligned {align="right"}

## Centered heading {align="center"}
Following paragraph (centered heading is H2).

## Banners
${banners}

::banner{color="blue" icon="🧪"}
Banner with an icon
::

::banner{color="green" icon="🧩"}
Multi-paragraph banner, first line.

Second paragraph must stay inside the same banner, not fall out below it.
::

> [!NOTE]
> GitHub NOTE alert → blue banner

> [!WARNING]
> GitHub WARNING alert → yellow banner

> [!CAUTION]
> GitHub CAUTION alert → pink-strong banner

## Quotes
::quote{size="large"}
This is a pull quote (large)

Second pull-quote paragraph stays in the same quote block.
::

> This is a normal block quote

## Headings (tight)
# Heading 1
Para after H1
## Heading 2
Para after H2
### Heading 3
Para after H3
#### Heading 4
Para after H4

## Lists
- Bullet 1
  - Bullet 1.1
    - Bullet 1.1.1
      - Bullet 1.1.1.1
- Bullet 2

1. Ordered 1
   1. Ordered 1.a
   2. Ordered 1.b
2. Ordered 2
3. Ordered 3 — numbering must read 1, 2, 3 and not restart

- [ ] Unchecked
- [x] Checked
  - [ ] Nested unchecked

## Toggles
::toggle{title="Simple toggle"}
Toggle body paragraph.
::

::toggle{title="Nested parent"}
  :::toggle{title="Nested child"}
  Inner toggle body
  :::
::

::toggle{title="Toggle with code"}
\`\`\`json
{
  "inside": "toggle",
  "lines": "must stay in one fence"
}
\`\`\`
::

## Code
A multi-line body must come back as ONE fence, not one fence per line.

\`\`\`json {lineNumbers}
{
  "lineNumbers": true,
  "ok": true,
  "note": "three body lines, one block"
}
\`\`\`

Two fences in a row must stay separate blocks with their own languages:

\`\`\`javascript
console.log('no line numbers')
console.log('second line of the same block')
\`\`\`

\`\`\`sql
SELECT 1
FROM dual
\`\`\`

## Divider
---

## Columns
::columns
  :::column{width="0.33"}
  Column A
  :::
  :::column{width="0.33"}
  Column B
  :::
  :::column{width="0.34"}
  Column C
  :::
::

## Tables
::table{widths="120,240,360"}
| Narrow | Medium | Wide explicit |
| --- | --- | --- |
| a | **bold** and ~~strike~~ | [pink]{color="pink"} |
| \`code\` | *italic* and [link](https://example.com) | ${mention} |
::

::table{widths="75,75,75"}
| A | B | C |
| --- | --- | --- |
| 1 | 2 | 3 |
::

::table{widths="708,75,75"}
| 90 | 10 | 10 |
| --- | --- | --- |
| long | x | y |
::

| Auto A | Auto somewhat longer header |
| --- | --- |
| 1 | 22 |

## Mermaid
\`\`\`mermaid
flowchart LR
  Local[CUFM] --> Compile[compileCufm]
  Compile --> Delta[Quill ops]
  Delta --> ClickUp
\`\`\`

## tldraw
\`\`\`tldraw {width="640"}
${TLDRAW_DOCTOR_SOURCE}
\`\`\`

## Button and frame
::button{url="https://example.com" color="#7B68EE"}
Doctor button
::

::frame{src="https://example.com" height="240"}
::

## End
If this paragraph is visible, the document compiled to the end.
`
}
