import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import type { Manifest } from './manifest.js'
import { plural } from '../util/plural.js'

/**
 * The archive's front page: what it contains and where to start. Regenerated
 * after every slice so a directory that began as one person's tasks and grew
 * into a team archive stays self-describing.
 */
export function renderRootReadme(manifest: Manifest): string {
  const ws = manifest.workspace
  const taskCount = Object.keys(manifest.tasks).length
  const docCount = Object.keys(manifest.docs).length
  const lines: string[] = [
    `# ClickUp export${ws ? `: ${ws.name}` : ''}`,
    '',
    `${plural(taskCount, 'task')} · ${plural(docCount, 'doc')} · generated by \`cup export\``,
    '',
    '## Slices',
    '',
    'Each slice is an index into the shared task store. Start from whichever matches what you are looking for.',
    '',
    '| Slice | Kind | Scope | Tasks | Exported |',
    '| --- | --- | --- | --- | --- |',
  ]
  // Docs live at docs/, not slices/; linked separately below.
  const slices = Object.entries(manifest.slices)
    .filter(([, s]) => s.kind !== 'docs')
    .sort((a, b) => a[0].localeCompare(b[0]))
  for (const [name, s] of slices) {
    lines.push(
      `| [${name}](slices/${name}/README.md) | ${s.kind} | ${s.scope} | ${s.taskCount} | ${s.exportedAt.slice(0, 10)} |`,
    )
  }
  if (docCount > 0) lines.push('', 'Docs: [docs/](docs/README.md)')
  lines.push(
    '',
    '## Layout',
    '',
    '- `tasks/<id>/` — one directory per task: `task.json` (lossless API payload), `task.md` (rendered), `comments.json` / `comments.md`, `attachments/`',
    '- `slices/<name>/README.md` — navigable index for one export scope',
    '- `manifest.json` — what has been exported and when; drives incremental re-runs',
    '',
    'Task ids match ClickUp URLs: `https://app.clickup.com/t/<id>` → `tasks/<id>/`.',
    '',
  )
  return lines.join('\n')
}

export function writeRootReadme(root: string, manifest: Manifest): void {
  writeFileSync(join(root, 'README.md'), renderRootReadme(manifest))
}
